In [1]:
from tensor import * 

### Basic arithmetic operations

In this section basic tensor calculation is described, Let $a_i \equiv (1,2,3), b_j \equiv (3,5,6).$ Defined as follows,

In [25]:
a = tensor(array([1,2,3]), "i", "d") # Define a rank 1 tensor has 1 subscript i.
b = tensor(array([3,5,6]), "j", "d") # Define a rank 1 tensor has 1 subscript j.

These arrays are one dimensional, so and can be written as vector $\boldsymbol{a}$ and $\boldsymbol{b}$, but each two tensor has odd subscripts, $i$ and $j$, which mean that two vectors are individual. Ordinary vector calulation can not handle the individual caluclation, but tensor can handle it, because tensor clearly specifies whether two tensor are individual with super or subscripts. 

Two tensor $a_i$ and $b_j$ can be output these infomation with print function.

In [26]:
print (a)

value----------
[1 2 3]

form----------
   
 a 
   i

shape---------
i : 3


In [27]:
print (b)

value----------
[3 5 6]

form----------
   
 a 
   j

shape---------
j : 3


Basic arithmetic operations of $a_i$ and $b_j$ as follows,

#### $a_i + b_j$ 

In [28]:
a + b

value----------
[[ 4.  6.  7.]
 [ 5.  7.  8.]
 [ 6.  8.  9.]]

form----------
   
 a 
   ij

shape---------
i : 3
j : 3

#### $a_i - b_j$ 

In [29]:
a - b

value----------
[[-2. -4. -5.]
 [-1. -3. -4.]
 [ 0. -2. -3.]]

form----------
   
 a 
   ij

shape---------
i : 3
j : 3

#### $a_i * b_j$

In [30]:
a * b # Correspond with outer product.

value----------
[[ 3  5  6]
 [ 6 10 12]
 [ 9 15 18]]

form----------
   
 tmp 
   ij

shape---------
i : 3
j : 3

#### $a_i ** b_j$

In [31]:
a ** b

value----------
[[   1.    1.    1.]
 [   8.   32.   64.]
 [  27.  243.  729.]]

form----------
   
 a 
   ij

shape---------
i : 3
j : 3

As you know these tensor calculation only indicate elementwize calculation. Though simple notation, tensor has abundant expressive power.

## Matrix product

Matrix product corresponds to the calculation between both of rank 2 tensor, which has two additional caractor and each one caractor is same and put odd location(super or sub script). Below example shows Matrix product of $c_i^j$ and $d_{jk}$, defined as follows,

In [32]:
c = tensor(array([[1,2,3], [4,5,6],   [7,8,9]]), "ij", "du")  # Define a rank 2 tensor has 2 subscript ij.
d = tensor(array([[6,7,8], [9,10,11], [12,13,14]]), "jk", "dd") # Define a rank 2 tensor has 2 subscript jk.

In tensor calculation, matrix product can be simple, as only multiply $c_i^j$ with $d_{jk}$ as follows,  

In [33]:
e = (c * d)
print e

value----------
[[  60.   66.   72.]
 [ 141.  156.  171.]
 [ 222.  246.  270.]]

form----------
   
 a 
   ik

shape---------
i : 3
k : 3


$e_{ik} = c_i^j d_{jk}$ was acquired. Same calclation using matrix notation with numpy is possible, 

In [34]:
c = array([[1,2,3], [4,5,6], [7,8,9]])
d = array([[6,7,8], [9,10,11], [12,13,14]])

print c.dot(d)

[[ 60  66  72]
 [141 156 171]
 [222 246 270]]


### Calculation of cross product with rank 3 permutation symbol. 

Using purmutation symbol(described at https://en.wikipedia.org/wiki/Levi-Civita_symbol), cross product can be calculated with tensor. Generate a rank 3 permutation symbol as follows,

In [35]:
ep = tensor_ps(3, idx="ijk", ud="uud") # ud=uud mean ep^ij_k

and two rank 1 tensor (vector) is also defined,

In [36]:
c = tensor([0,1,2], "i", "d")
d = tensor([3,4,5], "j", "d")

calculation and output result are performed as follows,

In [37]:
e = ep * c * d

In [38]:
print e


value----------
[-3  6 -3]

form----------
   
 a 
   k

shape---------
k : 3


This result corresponds to usual cross product as vector with numpy

In [39]:
print cross(array([0,1,2]), array([3,4,5]))

[-3  6 -3]


## Appendix

More example of implementation is introduced as http://qiita.com/uyuutosa 